# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WKWebView1' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WKWebView1

  pod 'SGNavigationProgress'
  
 target 'WKWebView1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WKWebView1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
